### ISSUE TITLE
Messages to and from the bot are cut off

### ISSUE THREAD

**Issue by ghost** [JFreegman/ToxBot#3]
Hey, so sorry in advance if I'm making a really stupid mistake and this is my fault, but here's my problem:

I have the qTox nightly binary installed from the repository (I'm running Ubuntu 14.10). It's completely up-to-date and stuff. I cloned this repository and built it, installing the latest toxcore and libsodium as I needed them (I used git checkout tags/1.0.0 on libsodium as it recommends). Everything built fine and the bot works, but my problem is that messages sent from the bot have the first four characters cut off (I get "lid command. Type help for a list of commands" from the bot), and messages sent to the bot appear to be blanked out. I think there's a version incompatibility here, but I can't be sure (I'm not very familiar with the Tox architecture). I tried Googling to see if this was a common bug, but I couldn't find anything (it doesn't help that your application is competing with something called Taxbot :P). I tried it with uTox and had the same issue. Do you have any idea what the problem could be? Thanks!

**Comment by JFreegman** [comment]
This is because qTox is running on the old API whereas groupbot has been ported to the new API. The two aren't compatible and unfortunately qTox is taking quite a while to be ported. Your two solutions would be to use a client that runs on the new API such as Toxic, or to checkout toxbot and toxcore to a commit before March 20ish.

**Comment by ghost** [comment]
Wow, quick reply. Thanks, I'll do that.
